# Generated by Django 4.0.3 on 2022-05-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_post_lieks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='lieks',
            new_name='likes',
        ),
    ]
